#!/usr/bin/env python
#
# Copyright (c) 2014, Arista Networks, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#  - Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#  - Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#  - Neither the name of Arista Networks nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ARISTA NETWORKS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#pylint: disable=W0703,W0402,E1103

import os
from string import Template

TEMP_CONFIG = '/tmp/tmp-config'

def main(attributes):
    '''Adds startup-config section.

    Appends config section to startup config based on the value of the
    'url' attribute.

    This action is dual-supervisor compatible.

    Accepts:
         A list of attributes; use attributes.get(<ATTRIBUTE_NAME>) to read attribute values

    Args:
        url: path to config snippet/template
        substitution_mode: loose|strict Default: loose
        variables: A list of variable: value substitutions
        Special_attributes: node: attributes.get('NODE') API: see documentation

    Example:
        ::

          -
            action: add_config
            attributes:
              url: files/templates/ma1.template
              variables:
                ipaddress: allocate('mgmt_subnet')
            name: "configure ma1"
            onstart: "Starting to configure ma1"
            onsuccess: "SUCCESS: ma1 configure"
            onfailure: "FAIL: IM provisioning@example.com for help"

    '''

    node = attributes.get('NODE')
    url = attributes.get('url')

    if not url:
        return 'Missing attribute(\'url\')'

    substitution_mode = attributes.get('substitution_mode', 'loose')
    if substitution_mode not in ['loose', 'strict']:
        return 'Invalid option specified for substitution_mode attribute'

    try:
        node.retrieve_url(url, TEMP_CONFIG)
    except Exception as exc:
        return 'Unable to retrieve config from URL (%s)' % exc

    contents = open(TEMP_CONFIG, 'r').read()

    variables = attributes.get('variables')
    if not variables:
        variables = {}

    if not isinstance(variables, dict):
        node.log_msg('Variables: %s' % variables)
        return 'Unable to perform variable substitution - invalid variables'
    try:
        if substitution_mode == 'strict':
            contents = Template(contents).substitute(variables)
        else:
            contents = Template(contents).safe_substitute(variables)
    except KeyError:
        return 'Unable to perform variable substitution - missing variable'

    node.append_startup_config_lines(contents.split('\n'))
    os.remove(TEMP_CONFIG)
