#!/usr/bin/env python 
#
# Copyright (c) 2014, Arista Networks, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#  - Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#  - Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#  - Neither the name of Arista Networks nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ARISTA NETWORKS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#pylint: disable=W0702

CLI_PLUGIN_DIR = '/usr/lib/python2.7/site-packages/CliPlugin'
PERSISTENT_PLUGIN_DIR = '/mnt/flash/.ztp-plugins'

import errno
import os
import urllib

def main(attributes): 
    '''Installs EOS CliPlugin.

    Installs CliPlugin based on the value of the
    'install_cli_plugin-url' attribute.

    Args:
       attributes: list of attributes; use attributes.get(<ATTRIBUTE_NAME>)
                   to read attribute values

       Special attributes:
           node: attributes.get('NODE')
                 API: see documentation

    Returns:
        0 - success
        1 - missing attribute('install_cli_plugin-url')
        2 - unable to create /mnt/flash/ztp-plugins
        3 - unable to retrieve extension from URL

    Raises:
        None
    '''

    url = attributes.get('install_cli_plugin-url')
    if not url:
        return 1
    
    try:
        os.makedirs(PERSISTENT_PLUGIN_DIR)
    except OSError, error:
        if error.errno != errno.EEXIST:
            return 2

    name = url.split('/')[ -1 ]
    try:
        urllib.urlretrieve(url, '%s/%s' % (PERSISTENT_PLUGIN_DIR,
                                           name))
    except:
        return 3
    
    lines = ['sudo cp %s/%s %s'  % (PERSISTENT_PLUGIN_DIR,
                                    name,
                                    CLI_PLUGIN_DIR)]
    
    attributes.get('NODE').append_rc_eos_lines(lines)
