#!/usr/bin/env python
#
# Copyright (c) 2015, Arista Networks, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#  - Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#  - Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#  - Neither the name of Arista Networks nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ARISTA NETWORKS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# pylint: disable=C0209

import io
import os

from six import raise_from

TEMP_FILE = "/tmp/tmp-run-script"


def main(attributes):
    """Runs a script in EOS from bash.

    This action is dual-supervisor compatible.

    Attributes:
        url: path to source script/template
        variables (optional):
             list of value substitutions (for a script template)

    Special_attributes:
        NODE: API object - see documentation for details

    Example:
        ::

          -
            action: run_bash_script
            attributes:
              url: files/scripts/install_script
              variables:
                version: 1.2.3
            name: 'install temp package'
    """

    node = attributes.get("NODE")
    url = attributes.get("url")

    if not url:
        raise RuntimeError("Missing attribute('url')")

    try:
        node.retrieve_url(url, TEMP_FILE)
    except Exception as exc:
        raise_from(RuntimeError("Unable to retrieve config from URL"), exc)

    with io.open(TEMP_FILE, encoding="utf8") as exec_file:
        contents = exec_file.read()

    variables = attributes.get("variables")
    if not variables:
        variables = {}

    if not isinstance(variables, dict):
        node.log_msg("Variables: {}".format(variables))
        raise RuntimeError("Unable to perform variable substitution - invalid variables")

    contents = node.substitute(contents, variables)

    with io.open(TEMP_FILE, "w", encoding="utf8") as exec_file:
        exec_file.write(contents)

    os.chmod(TEMP_FILE, 0o777)
    (cmd, code, out, err) = node.bash_cmds([TEMP_FILE])

    if code or err:
        raise RuntimeError(
            "Running {} in bash failed return_code={}, stdout={}, stderr={})".format(
                cmd, code, out, err
            )
        )

    # Only remove this in case everything else succeeded
    # for debugging purposes
    os.remove(TEMP_FILE)
